spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/azmur_db
    username: postgres
    password: root123
  application:
    name: azmur
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my_token:
  key: my-very-secret-key-with-32-characters-minimum
  expire_time: 3600000
  refresh_expire_time: 86400000